//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Bloc : MonoBehaviour
{
	float initialX;
	float initialY;

	public Bloc ()
	{

	}

	public void SetInitialCoordinates(float x, float y)
	{
		initialX = x;
		initialY = y;
	}

	public virtual void Restart()
	{
		Vector2 temp = transform.position;
		temp.x = initialX;
		temp.y = initialY;
		transform.position = temp;
		gameObject.SetActive(true);
	}
}

