//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class BlockManager
{
	private static BlockManager instance;
	
	private BlockManager() {}
	
	public static BlockManager Instance
	{
		get 
		{
			if (instance == null)
			{
				blocs = new List<Bloc>();
				instance = new BlockManager();
			}
			return instance;
		}
	}

	//------------------------------------------------------------------
	private static List<Bloc> blocs;

	public void AddBlock(Bloc bloc)
	{
		blocs.Add (bloc);
	}

	public void RemoveBlock(Bloc bloc)
	{
		blocs.Remove(bloc);
	}

	public void Restart()
	{
		foreach(Bloc bloc in blocs)
		{
			if(bloc.hasBeenPlaced)
			{
				bloc.gameObject.SetActive(false);
			}
			else
				bloc.Restart();
		}
	}

	public void ResetPlacedBlocks()
	{
		foreach(Bloc bloc in blocs)
		{
			if(bloc.hasBeenPlaced)
			{
				bloc.gameObject.SetActive(false);
			}
		}
	}

	public void Clear()
	{
		blocs.Clear();
	}
}

